export const APPEND_NOTIFICATIONS = 'APPEND_NOTIFICATIONS';
export const MARK_AS_READ = 'MARK_AS_READ';
export const UPDATE_REQUESTING = 'UPDATE_REQUESTING';
export const SET_URL = 'SET_URL';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const UPDATE_TOTAL_PAGES = 'UPDATE_TOTAL_PAGES';
