export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const SET_AS_ANSWERED = 'SET_AS_ANSWERED';
export const SET_QUESTIONS_URL = 'SET_QUESTIONS_URL';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const UPDATE_REQUESTING = 'UPDATE_REQUESTING';

export const SET_EDITOR_CONTENT = 'SET_EDITOR_CONTENT';
export const UPDATE_EDITOR_CONTENT = 'UPDATE_EDITOR_CONTENT';
export const SET_EDITOR_QUESTION = 'SET_EDITOR_QUESTION';