// questionList
export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const SET_AS_ANSWERED = 'SET_AS_ANSWERED';
export const SET_QUESTIONS_URL = 'SET_QUESTIONS_URL';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const UPDATE_REQUESTING = 'UPDATE_REQUESTING';
export const SET_SHOW_ANSWER_CREATE_MODAL = 'SET_SHOW_ANSWER_CREATE_MODAL';
export const SET_CREATE_MODAL_METHOD = 'SET_CREATE_MODAL_METHOD';
export const SET_CREATE_MODAL_URL = 'SET_CREATE_MODAL_URL';

// editor
export const SET_EDITOR_CONTENT = 'SET_EDITOR_CONTENT';
export const UPDATE_EDITOR_CONTENT = 'UPDATE_EDITOR_CONTENT';
export const SET_EDITOR_QUESTION = 'SET_EDITOR_QUESTION';
export const SET_EDITOR_ELEMENT = 'SET_EDITOR_ELEMENT';
export const SET_CREDENTIAL_ID = 'SET_CREDENTIAL_ID';

// feed
export const SET_SHOW_ANSWER_SHOW_MODAL = 'SET_SHOW_ANSWER_SHOW_MODAL';
export const SET_SHOWED_ANSWER = 'SET_SHOWED_ANSWER';

// moreMenu
export const SET_ACTIVE_MORE_MENU = 'SET_ACTIVE_MORE_MENU';
