// credentials
export const SET_VISIBLE = 'SET_VISIBLE';
export const SET_CREDENTIAL_INPUT = 'SET_CREDENTIAL_INPUT';
export const SET_REQUESTING = 'SET_REQUESTING';
export const SET_SUBMITTING = 'SET_SUBMITTING';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const SET_CREDENTIALS_URL = 'SET_CREDENTIALS_URL';
export const PUSH_CREDENTIALS = 'PUSH_CREDENTIALS';
export const SET_SELECTED_CREDENTIAL = 'SET_SELECTED_CREDENTIAL';
export const SET_SELECTED_CREDENTIAL_TEXT = 'SET_SELECTED_CREDENTIAL_TEXT';
export const SET_SHOW_ADD_CREDENTIAL_OVERLAY = 'SET_SHOW_ADD_CREDENTIAL_OVERLAY';
export const SET_FORM_INPUT = 'SET_FORM_INPUT';
export const PUSH_CREDENTIAL = 'PUSH_CREDENTIAL';
export const UNSHIFT_CREDENTIAL = 'UNSHIFT_CREDENTIAL';
