// credentials
export const SET_VISIBLE = 'SET_VISIBLE';
export const SET_CREDENTIAL_INPUT = 'SET_CREDENTIAL_INPUT';
export const SET_REQUESTING = 'SET_REQUESTING';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const SET_CREDENTIALS_URL = 'SET_CREDENTIALS_URL';
export const PUSH_CREDENTIALS = 'PUSH_CREDENTIALS';
export const SET_SELECTED_CREDENTIAL = 'SET_SELECTED_CREDENTIAL';
export const SET_SELECTED_CREDENTIAL_TEXT = 'SET_SELECTED_CREDENTIAL_TEXT';
